language: go

sudo: required

env:
  global:
  - genv=test123

before_install:
- echo "common before install"

install:
- echo "common install"

before_script:
- echo "common before script"

script:
- echo "common script"

after_success:
- echo "common after success"

jobs:
  include:
  - stage: precheck
    install:
    - echo "install deps"
    script:
    - echo "run checks"
  - stage: build and test
    install:
    - echo "install tools"
    script: 
    - echo "script 1"
    - echo global $genv
  - stage: build and test
    install: skip
    script:
    - echo "script 2"
    - echo global $genv
    after_success:
    - echo "after success"
  - stage: deploy 
    script:
    - echo "deploy something"
